import { listCollaborators, type Collaborator } from './collaborators'
import { listEvents, type RentalEvent } from './events'
import { supabase } from './supabase'
export type CollectionItem={item_id:string;internal_code:string;description:string;checked:boolean;apparent_damage:boolean;damage_notes:string|null}
export type CollectionDetails={items:CollectionItem[];collaborators:Collaborator[];movement:{id:string;occurred_at:string;confirmation:string|null}|null}
type DepartureRow={item_id:string;items:{internal_code:string;description:string}}
function client(){if(!supabase)throw new Error('Serviço não configurado.');return supabase}
export async function listCollectionEvents(){const [events,moves]=await Promise.all([listEvents(),client().from('movements').select('event_id,movement_type')]);if(moves.error)throw new Error(moves.error.message);const out=new Set((moves.data??[]).filter(x=>x.movement_type==='SAIDA').map(x=>x.event_id));const returned=new Set((moves.data??[]).filter(x=>x.movement_type==='RETORNO').map(x=>x.event_id));return events.filter(e=>out.has(e.id)&&!returned.has(e.id))}
export async function loadCollection(event:RentalEvent):Promise<CollectionDetails>{const [departure,checks,movement,people]=await Promise.all([client().from('movement_items').select('item_id,items!movement_items_tenant_item_fk(internal_code,description),movements!movement_items_tenant_movement_fk!inner(event_id,movement_type)').eq('movements.event_id',event.id).eq('movements.movement_type','SAIDA'),client().from('return_collection_checks').select('item_id,apparent_damage,damage_notes').eq('event_id',event.id),client().from('movements').select('id,occurred_at,confirmation').eq('event_id',event.id).eq('movement_type','COLETA_RETORNO').maybeSingle(),listCollaborators()]);const error=departure.error??checks.error??movement.error;if(error)throw new Error(error.message);const map=new Map((checks.data??[]).map(x=>[x.item_id,x]));return{items:((departure.data??[])as unknown as DepartureRow[]).map((row)=>{const check=map.get(row.item_id);return{item_id:row.item_id,internal_code:row.items.internal_code,description:row.items.description,checked:Boolean(check),apparent_damage:check?.apparent_damage??false,damage_notes:check?.damage_notes??null}}),collaborators:people.filter(p=>p.organization_id===event.organization_id&&p.active),movement:movement.data}}
export async function scanCollection(eventId:string,code:string,damage:boolean,notes:string){const{error}=await client().rpc('scan_return_collection_item',{target_event_id:eventId,scanned_code:code,target_damage:damage,target_notes:notes||null});if(error)throw new Error(error.message)}
export async function finishCollection(eventId:string,collaboratorId:string,notes:string,incomplete:boolean){const{error}=await client().rpc('finalize_return_collection',{target_event_id:eventId,responsible_collaborator_id:collaboratorId,target_notes:notes||null,allow_incomplete:incomplete});if(error)throw new Error(error.message)}
