import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, MapPin, X } from 'lucide-react'
import { listAgendaEvents, type EventStatus, type RentalEvent } from '../lib/events'

type AgendaMode = 'day' | 'week' | 'month'
const statuses: Array<[EventStatus, string]> = [['PLANEJADO', 'Planejado'], ['CONFIRMADO', 'Confirmado'], ['EM_ANDAMENTO', 'Em andamento'], ['CONCLUIDO', 'Concluído'], ['CANCELADO', 'Cancelado']]
const message = (error: unknown) => error instanceof Error ? error.message : 'Não foi possível carregar a agenda.'
const startOfDay = (date: Date) => new Date(date.getFullYear(), date.getMonth(), date.getDate())
const addDays = (date: Date, days: number) => { const next = new Date(date); next.setDate(next.getDate() + days); return next }
const startOfWeek = (date: Date) => { const day = startOfDay(date); const weekday = day.getDay() || 7; return addDays(day, 1 - weekday) }
const localDateValue = (date: Date) => { const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 10) }
const overlapsDay = (event: RentalEvent, date: Date) => new Date(event.assembly_at) < addDays(startOfDay(date), 1) && new Date(event.disassembly_at) >= startOfDay(date)
const statusLabel = (status: EventStatus) => statuses.find(([value]) => value === status)?.[1] ?? status

export function AgendaPage({ onOpenEvents }: { onOpenEvents: () => void }) {
  const [mode, setMode] = useState<AgendaMode>('week'); const [anchor, setAnchor] = useState(() => new Date()); const [status, setStatus] = useState<EventStatus | ''>(''); const [events, setEvents] = useState<RentalEvent[]>([]); const [selected, setSelected] = useState<RentalEvent>(); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const range = useMemo(() => {
    if (mode === 'day') { const start = startOfDay(anchor); return { start, end: addDays(start, 1), days: [start] } }
    if (mode === 'week') { const start = startOfWeek(anchor); return { start, end: addDays(start, 7), days: Array.from({ length: 7 }, (_, index) => addDays(start, index)) } }
    const monthStart = new Date(anchor.getFullYear(), anchor.getMonth(), 1); const start = startOfWeek(monthStart); return { start, end: addDays(start, 42), days: Array.from({ length: 42 }, (_, index) => addDays(start, index)) }
  }, [anchor, mode])
  const rangeStart = range.start.toISOString(); const rangeEnd = range.end.toISOString()
  useEffect(() => { let active = true; setLoading(true); setError(''); void listAgendaEvents(rangeStart, rangeEnd, status || undefined).then((data) => { if (active) setEvents(data) }).catch((reason: unknown) => { if (active) setError(message(reason)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [rangeStart, rangeEnd, status])
  function navigate(direction: number) { setAnchor((current) => { const next = new Date(current); if (mode === 'day') next.setDate(next.getDate() + direction); else if (mode === 'week') next.setDate(next.getDate() + direction * 7); else next.setMonth(next.getMonth() + direction); return next }) }
  const title = mode === 'day' ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'full' }).format(anchor) : mode === 'week' ? `${range.start.toLocaleDateString('pt-BR')} a ${addDays(range.end, -1).toLocaleDateString('pt-BR')}` : new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' }).format(anchor)

  return <><div className="title-row clients-title"><div><h1>Agenda</h1><p>Montagens, eventos e desmontagens em um único calendário.</p></div><button className="primary" onClick={onOpenEvents}><CalendarDays /> Novo evento</button></div>
    <section className="panel agenda-controls"><div className="agenda-navigation"><button onClick={() => navigate(-1)} aria-label="Período anterior"><ChevronLeft /></button><button className="secondary" onClick={() => setAnchor(new Date())}>Hoje</button><button onClick={() => navigate(1)} aria-label="Próximo período"><ChevronRight /></button><strong>{title}</strong></div><div className="agenda-filters"><input type="date" value={localDateValue(anchor)} onChange={(event) => setAnchor(new Date(`${event.target.value}T12:00:00`))} /><select value={status} onChange={(event) => setStatus(event.target.value as EventStatus | '')}><option value="">Todos os status</option>{statuses.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><div className="agenda-modes">{([['day', 'Dia'], ['week', 'Semana'], ['month', 'Mês']] as Array<[AgendaMode, string]>).map(([value, label]) => <button className={mode === value ? 'agenda-mode agenda-mode--active' : 'agenda-mode'} onClick={() => setMode(value)} key={value}>{label}</button>)}</div></div></section>
    {error ? <div className="data-error">{error}</div> : null}{loading ? <p className="empty-state">Carregando agenda…</p> : mode === 'day' ? <section className="panel agenda-day"><header><h2>Operações do dia</h2><span>{events.length} eventos no período</span></header>{events.length === 0 ? <div className="clients-empty"><CalendarDays /><strong>Nenhum evento neste dia</strong></div> : events.map((event) => <button className="agenda-day-event" onClick={() => setSelected(event)} key={event.id}><span className="agenda-event-time"><strong>{new Date(event.assembly_at).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</strong><small>montagem</small></span><i className={`agenda-status-dot agenda-status-dot--${event.status.toLowerCase()}`} /><span><strong>{event.name}</strong><small>{event.client_name} · {event.venue || event.address || 'Local não informado'}</small></span><span className={`event-status event-status--${event.status.toLowerCase()}`}>{statusLabel(event.status)}</span></button>)}</section> : <section className={`panel agenda-calendar agenda-calendar--${mode}`}><header>{range.days.slice(0, 7).map((date) => <span key={date.toISOString()}>{new Intl.DateTimeFormat('pt-BR', { weekday: 'short' }).format(date)}</span>)}</header><div>{range.days.map((date) => { const dayEvents = events.filter((event) => overlapsDay(event, date)); const outside = mode === 'month' && date.getMonth() !== anchor.getMonth(); const today = localDateValue(date) === localDateValue(new Date()); return <article className={`${outside ? 'agenda-cell agenda-cell--outside' : 'agenda-cell'} ${today ? 'agenda-cell--today' : ''}`} key={date.toISOString()}><strong>{mode === 'week' ? <>{date.getDate()}<small>{new Intl.DateTimeFormat('pt-BR', { month: 'short' }).format(date)}</small></> : date.getDate()}</strong><div>{dayEvents.slice(0, mode === 'month' ? 3 : 8).map((event) => <button className={`agenda-chip agenda-chip--${event.status.toLowerCase()}`} title={event.name} onClick={() => setSelected(event)} key={event.id}><time>{new Date(event.starts_at).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</time>{event.name}</button>)}{dayEvents.length > (mode === 'month' ? 3 : 8) ? <small>+ {dayEvents.length - (mode === 'month' ? 3 : 8)} eventos</small> : null}</div></article> })}</div></section>}
    {selected ? <div className="modal-backdrop"><section className="client-modal agenda-detail" role="dialog" aria-modal="true"><header><div><span><CalendarDays /></span><div><h2>{selected.name}</h2><p>{selected.client_name}</p></div></div><button onClick={() => setSelected(undefined)}><X /></button></header><div className="agenda-detail-body"><span className={`event-status event-status--${selected.status.toLowerCase()}`}>{statusLabel(selected.status)}</span><p><Clock3 /> Montagem: {new Date(selected.assembly_at).toLocaleString('pt-BR')}</p><p><CalendarDays /> Evento: {new Date(selected.starts_at).toLocaleString('pt-BR')} até {new Date(selected.ends_at).toLocaleString('pt-BR')}</p><p><Clock3 /> Desmontagem: {new Date(selected.disassembly_at).toLocaleString('pt-BR')}</p><p><MapPin /> {selected.venue || selected.address || 'Local não informado'}</p></div><footer><button className="secondary" onClick={() => setSelected(undefined)}>Fechar</button><button className="primary" onClick={onOpenEvents}>Abrir cadastro do evento</button></footer></section></div> : null}</>
}
