import { type FormEvent, useEffect, useState } from 'react'
import { Check, CheckCircle2, LogOut, PackageCheck, Truck, UserRound } from 'lucide-react'
import { finalizeDeparture, listDepartureEvents, loadDepartureDetails, type DepartureDetails } from '../lib/departure'
import type { RentalEvent } from '../lib/events'

const message = (error: unknown) => error instanceof Error ? error.message : 'Não foi possível concluir a operação.'

export function DeparturePage() {
  const [events, setEvents] = useState<RentalEvent[]>([]); const [eventId, setEventId] = useState(''); const [details, setDetails] = useState<DepartureDetails>()
  const [collaboratorId, setCollaboratorId] = useState(''); const [receiverName, setReceiverName] = useState(''); const [notes, setNotes] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  const selectedEvent = events.find((event) => event.id === eventId); const checkedCount = details?.items.filter((item) => item.checked).length ?? 0; const total = details?.items.length ?? 0; const ready = total > 0 && checkedCount === total && Boolean(collaboratorId) && !details?.movement

  useEffect(() => { let active = true; void listDepartureEvents().then((data) => { if (active) { setEvents(data); setEventId(data[0]?.id ?? '') } }).catch((reason: unknown) => { if (active) setError(message(reason)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [])
  useEffect(() => { if (!selectedEvent) { setDetails(undefined); return }; let active = true; setLoading(true); setError(''); setSuccess(''); void loadDepartureDetails(selectedEvent).then((data) => { if (active) { setDetails(data); setCollaboratorId(data.collaborators[0]?.id ?? '') } }).catch((reason: unknown) => { if (active) setError(message(reason)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [selectedEvent])
  async function submit(event: FormEvent) { event.preventDefault(); if (!selectedEvent || !ready) return; setSaving(true); setError(''); try { await finalizeDeparture(selectedEvent.id, collaboratorId, receiverName, notes); setDetails(await loadDepartureDetails(selectedEvent)); setSuccess('Saída registrada com sucesso. Os equipamentos agora estão em uso.') } catch (reason) { setError(message(reason)) } finally { setSaving(false) } }

  return <><div className="title-row clients-title"><div><h1>Saída</h1><p>Registro da entrega física dos equipamentos separados.</p></div></div>
    <section className="separation-event panel"><label className="field">Evento<select value={eventId} onChange={(event) => setEventId(event.target.value)}><option value="">Selecione um evento</option>{events.map((event) => <option value={event.id} key={event.id}>{event.name} · {new Date(event.starts_at).toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short' })}</option>)}</select></label>{selectedEvent ? <div><strong>{selectedEvent.client_name}</strong><span>{selectedEvent.venue || selectedEvent.address || 'LOCAL NÃO INFORMADO'}</span><small>Saída prevista: {new Date(selectedEvent.assembly_at).toLocaleString('pt-BR')}</small></div> : null}</section>
    {error ? <div className="data-error" role="alert">{error}</div> : null}{success ? <div className="data-success"><Check /> {success}</div> : null}
    {!loading && events.length === 0 ? <div className="clients-empty panel"><Truck /><strong>Nenhum evento disponível para saída</strong><p>Reserve e separe os equipamentos de um evento ativo.</p></div> : selectedEvent && details ? <div className="departure-grid">
      <section className="panel departure-items"><header><div><PackageCheck /><span><h2>Equipamentos separados</h2><small>{checkedCount} de {total} conferidos</small></span></div><strong className={checkedCount === total && total > 0 ? 'departure-ready' : 'departure-pending'}>{checkedCount === total && total > 0 ? 'Pronto para saída' : 'Separação incompleta'}</strong></header><div>{details.items.map((item) => <article key={item.item_id}><span className={item.checked ? 'departure-check departure-check--ok' : 'departure-check'}>{item.checked ? <Check /> : '!'}</span><div><strong>{item.internal_code} · {item.description}</strong><small>Condição: {item.condition}</small></div><em>{item.checked ? 'Separado' : 'Pendente'}</em></article>)}</div></section>
      <section className="panel departure-confirmation">{details.movement ? <div className="departure-complete"><CheckCircle2 /><h2>Saída do galpão registrada</h2><p>{new Date(details.movement.occurred_at).toLocaleString('pt-BR')}</p><strong>{details.movement.receiver_name ? `Retirada/transporte: ${details.movement.receiver_name}` : 'Responsável pela retirada não informado'}</strong><small>Esta operação não pode ser repetida.</small></div> : <form onSubmit={(event) => void submit(event)}><header><LogOut /><div><h2>Confirmar saída do galpão</h2><p>Registre quem liberou os equipamentos para transporte.</p></div></header><label className="field"><UserRound size={15} /> Liberado por — equipe do galpão<select required value={collaboratorId} onChange={(event) => setCollaboratorId(event.target.value)}><option value="">Selecione um colaborador</option>{details.collaborators.map((person) => <option value={person.id} key={person.id}>{person.name} · {person.job_role}</option>)}</select></label><label className="field">Responsável pela retirada/transporte — opcional<input placeholder="EX.: MOTORISTA OU TRANSPORTADORA" value={receiverName} onChange={(event) => setReceiverName(event.target.value.toLocaleUpperCase('pt-BR'))} /></label><label className="field">Observações<textarea rows={4} value={notes} onChange={(event) => setNotes(event.target.value.toLocaleUpperCase('pt-BR'))} /></label>{details.collaborators.length === 0 ? <div className="data-error">Cadastre um colaborador ativo para registrar a liberação.</div> : null}<button className="primary departure-submit" disabled={!ready || saving}><Truck /> {saving ? 'Registrando…' : 'Confirmar saída do galpão'}</button></form>}</section>
    </div> : loading ? <p className="empty-state">Carregando saída…</p> : null}</>
}
