import { useEffect, useMemo, useState } from 'react'
import { CalendarClock, Check, PackagePlus, Search, Trash2, X } from 'lucide-react'
import { addEquipmentReservations, loadReservationManager, removeEquipmentReservation, type EquipmentReservation } from '../lib/reservations'
import type { EquipmentItem } from '../lib/equipment'
import type { RentalEvent } from '../lib/events'

const localDateTime = (value: string) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16) }
const message = (error: unknown) => error instanceof Error ? error.message : 'Não foi possível concluir a operação.'
const blockedConditions = new Set(['DANIFICADO', 'EXTRAVIADO', 'BAIXADO'])

export function EventEquipmentModal({ event, onClose }: { event: RentalEvent; onClose: () => void }) {
  const [items, setItems] = useState<EquipmentItem[]>([]); const [reservations, setReservations] = useState<EquipmentReservation[]>([])
  const [departure, setDeparture] = useState(localDateTime(event.assembly_at)); const [returnAt, setReturnAt] = useState(localDateTime(event.disassembly_at)); const [bufferHours, setBufferHours] = useState(4)
  const [selected, setSelected] = useState<Set<string>>(() => new Set()); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  async function refresh() { const data = await loadReservationManager(event.organization_id); setItems(data.items); setReservations(data.reservations) }
  useEffect(() => { let active = true; void loadReservationManager(event.organization_id).then((data) => { if (active) { setItems(data.items); setReservations(data.reservations) } }).catch((reason: unknown) => { if (active) setError(message(reason)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [event.organization_id])
  const currentReservations = reservations.filter((reservation) => reservation.event_id === event.id); const currentIds = new Set(currentReservations.map((reservation) => reservation.item_id))
  const conflictByItem = useMemo(() => { const start = new Date(departure).getTime(); const finish = new Date(returnAt).getTime() + bufferHours * 60 * 60_000; const conflicts = new Map<string, string>(); for (const reservation of reservations) { if (!reservation.active || reservation.event_id === event.id) continue; const reservedStart = new Date(reservation.planned_departure_at).getTime(); const reservedFinish = new Date(reservation.planned_return_at).getTime() + reservation.logistics_buffer_hours * 60 * 60_000; if (start < reservedFinish && reservedStart < finish) conflicts.set(reservation.item_id, reservation.event_name) } return conflicts }, [reservations, event.id, departure, returnAt, bufferHours])
  const filtered = useMemo(() => { const term = search.trim().toLocaleLowerCase('pt-BR'); return term ? items.filter((item) => [item.internal_code, item.description, item.category_name, item.brand, item.model].some((value) => value?.toLocaleLowerCase('pt-BR').includes(term))) : items }, [items, search])
  const periodValid = new Date(departure).getTime() < new Date(returnAt).getTime()
  function toggle(itemId: string) { setSelected((current) => { const next = new Set(current); if (next.has(itemId)) next.delete(itemId); else next.add(itemId); return next }) }
  async function reserve() { if (!periodValid || selected.size === 0) return; setSaving(true); setError(''); try { await addEquipmentReservations(event.id, [...selected], new Date(departure).toISOString(), new Date(returnAt).toISOString(), bufferHours); setSelected(new Set()); await refresh() } catch (reason) { setError(message(reason)); await refresh() } finally { setSaving(false) } }
  async function remove(id: string) { setSaving(true); setError(''); try { await removeEquipmentReservation(id); await refresh() } catch (reason) { setError(message(reason)) } finally { setSaving(false) } }

  return <div className="modal-backdrop"><section className="client-modal reservation-modal" role="dialog" aria-modal="true" aria-labelledby="reservation-title"><header><div><span><CalendarClock /></span><div><h2 id="reservation-title">Equipamentos · {event.name}</h2><p>Selecione somente unidades disponíveis no período operacional.</p></div></div><button aria-label="Fechar" onClick={onClose}><X /></button></header><div className="reservation-content">
    {error ? <div className="data-error" role="alert">{error}</div> : null}<div className="reservation-period"><label className="field">Saída prevista<input type="datetime-local" value={departure} onChange={(e) => setDeparture(e.target.value)} /></label><label className="field">Retorno previsto<input type="datetime-local" value={returnAt} onChange={(e) => setReturnAt(e.target.value)} /></label><label className="field">Folga logística<select value={bufferHours} onChange={(e) => setBufferHours(Number(e.target.value))}><option value={0}>Sem folga</option><option value={2}>2 horas</option><option value={4}>4 horas</option><option value={8}>8 horas</option><option value={12}>12 horas</option><option value={24}>24 horas</option></select></label></div>{!periodValid ? <div className="data-error">O retorno deve acontecer depois da saída.</div> : null}
    <div className="reserved-section"><h3>Já reservados neste evento <span>{currentReservations.length}</span></h3>{currentReservations.length === 0 ? <p>Nenhum equipamento reservado.</p> : <div>{currentReservations.map((reservation) => <article key={reservation.id}><Check /><span><strong>{reservation.item.internal_code}</strong><small>{reservation.item.description}</small></span><button aria-label={`Remover ${reservation.item.internal_code}`} disabled={saving} onClick={() => void remove(reservation.id)}><Trash2 /></button></article>)}</div>}</div>
    <div className="reservation-toolbar"><label className="clients-search"><Search /><input placeholder="Buscar equipamento" value={search} onChange={(e) => setSearch(e.target.value)} /></label><button className="primary" disabled={saving || !periodValid || selected.size === 0} onClick={() => void reserve()}><PackagePlus /> Reservar {selected.size || ''}</button></div>
    <div className="equipment-picker">{loading ? <p>Carregando disponibilidade…</p> : filtered.map((item) => { const conflict = conflictByItem.get(item.id); const conditionBlocked = blockedConditions.has(item.condition); const alreadyReserved = currentIds.has(item.id); const unavailable = Boolean(conflict || conditionBlocked || alreadyReserved); return <label className={unavailable ? 'equipment-option equipment-option--blocked' : 'equipment-option'} key={item.id}><input type="checkbox" disabled={unavailable} checked={selected.has(item.id)} onChange={() => toggle(item.id)} /><span><strong>{item.internal_code} · {item.description}</strong><small>{item.category_name} · {[item.brand, item.model].filter(Boolean).join(' ') || 'SEM MARCA/MODELO'}</small></span><em>{alreadyReserved ? 'Neste evento' : conflict ? `Conflito: ${conflict}` : conditionBlocked ? item.condition : 'Disponível'}</em></label> })}</div>
  </div><footer className="reservation-footer"><button className="secondary" onClick={onClose}>Fechar</button></footer></section></div>
}
