import { type FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { AlertTriangle, Check, CheckCircle2, QrCode, RotateCcw, ScanLine, Undo2 } from 'lucide-react'
import { finalizeReturn, listReturnEvents, loadReturnDetails, scanReturnItem, undoReturnCheck, type ReturnCondition, type ReturnDetails } from '../lib/returns'
import type { RentalEvent } from '../lib/events'

const conditions: Array<[ReturnCondition, string]> = [['OTIMO', 'Ótimo'], ['BOM', 'Bom'], ['REGULAR', 'Regular'], ['DANIFICADO', 'Danificado'], ['EXTRAVIADO', 'Extraviado']]
const message = (error: unknown) => error instanceof Error ? error.message : 'Não foi possível concluir a operação.'

export function ReturnPage() {
  const [events, setEvents] = useState<RentalEvent[]>([]); const [eventId, setEventId] = useState(''); const [details, setDetails] = useState<ReturnDetails>()
  const [code, setCode] = useState(''); const [condition, setCondition] = useState<ReturnCondition>('BOM'); const [defect, setDefect] = useState(''); const [collaboratorId, setCollaboratorId] = useState(''); const [notes, setNotes] = useState('')
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const inputRef = useRef<HTMLInputElement>(null)
  const selectedEvent = events.find((event) => event.id === eventId); const checkedCount = details?.items.filter((item) => item.check_id).length ?? 0; const total = details?.items.length ?? 0; const complete = total > 0 && checkedCount === total
  const orderedItems = useMemo(() => [...(details?.items ?? [])].sort((a, b) => Number(Boolean(a.check_id)) - Number(Boolean(b.check_id)) || a.internal_code.localeCompare(b.internal_code, 'pt-BR')), [details?.items])
  useEffect(() => { let active = true; void listReturnEvents().then((data) => { if (active) { setEvents(data); setEventId(data[0]?.id ?? '') } }).catch((reason: unknown) => { if (active) setError(message(reason)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [])
  useEffect(() => { if (!selectedEvent) { setDetails(undefined); return }; let active = true; setLoading(true); setError(''); void loadReturnDetails(selectedEvent).then((data) => { if (active) { setDetails(data); setCollaboratorId(data.collaborators[0]?.id ?? '') } }).catch((reason: unknown) => { if (active) setError(message(reason)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [selectedEvent])
  async function refresh() { if (selectedEvent) setDetails(await loadReturnDetails(selectedEvent)) }
  async function scan(event: FormEvent) { event.preventDefault(); if (!eventId || !code.trim()) return; setSaving(true); setError(''); setSuccess(''); try { await scanReturnItem(eventId, code, condition, defect); setSuccess(`${code.trim().toLocaleUpperCase('pt-BR')} conferido no retorno.`); setCode(''); setDefect(''); setCondition('BOM'); await refresh() } catch (reason) { setError(message(reason)) } finally { setSaving(false); inputRef.current?.focus() } }
  async function undo(id: string) { setSaving(true); setError(''); try { await undoReturnCheck(id); await refresh() } catch (reason) { setError(message(reason)) } finally { setSaving(false) } }
  async function finish() { if (!complete || !collaboratorId || !selectedEvent) return; setSaving(true); setError(''); try { await finalizeReturn(selectedEvent.id, collaboratorId, notes); await refresh(); setSuccess('Retorno finalizado. Itens danificados foram enviados para manutenção.') } catch (reason) { setError(message(reason)) } finally { setSaving(false) } }

  return <><div className="title-row clients-title"><div><h1>Retorno e conferência</h1><p>Registro das condições devolvidas e entrada no galpão.</p></div></div><section className="separation-event panel"><label className="field">Evento com saída registrada<select value={eventId} onChange={(event) => setEventId(event.target.value)}><option value="">Selecione um evento</option>{events.map((event) => <option value={event.id} key={event.id}>{event.name} · {event.client_name}</option>)}</select></label>{selectedEvent ? <div><strong>{selectedEvent.name}</strong><span>{selectedEvent.venue || selectedEvent.address || 'LOCAL NÃO INFORMADO'}</span><small>Retorno previsto: {new Date(selectedEvent.disassembly_at).toLocaleString('pt-BR')}</small></div> : null}</section>
    {error ? <div className="data-error" role="alert">{error}</div> : null}{success ? <div className="data-success"><Check /> {success}</div> : null}
    {!loading && events.length === 0 ? <div className="clients-empty panel"><Undo2 /><strong>Nenhum evento aguardando retorno</strong><p>Registre primeiro a saída dos equipamentos.</p></div> : selectedEvent && details ? <>{details.movement ? <section className="panel return-complete"><CheckCircle2 /><h2>Retorno finalizado</h2><p>{new Date(details.movement.occurred_at).toLocaleString('pt-BR')}</p><strong>{total} equipamentos processados</strong></section> : <>
      <section className="separation-progress"><article><Undo2 /><span><strong>{checkedCount} de {total}</strong><small>itens conferidos no retorno</small></span></article><div><span><strong>{total ? Math.round(checkedCount / total * 100) : 0}%</strong><small>{complete ? 'Pronto para finalizar' : `${total - checkedCount} pendentes`}</small></span><div className="progress"><i style={{ width: `${total ? checkedCount / total * 100 : 0}%` }} /></div></div></section>
      <form className="return-scanner-form" onSubmit={(event) => void scan(event)}><ScanLine /><label className="field">QR ou código interno<input ref={inputRef} autoFocus required value={code} onChange={(event) => setCode(event.target.value.toLocaleUpperCase('pt-BR'))} placeholder="LEIA OU DIGITE O CÓDIGO" /></label><label className="field">Condição<select value={condition} onChange={(event) => setCondition(event.target.value as ReturnCondition)}>{conditions.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>{condition === 'DANIFICADO' || condition === 'EXTRAVIADO' ? <label className="field return-defect">{condition === 'DANIFICADO' ? 'Descrição do defeito' : 'Observação do extravio'}<input required value={defect} onChange={(event) => setDefect(event.target.value.toLocaleUpperCase('pt-BR'))} /></label> : null}<button className="primary" disabled={saving || !code.trim()}><QrCode /> Conferir</button></form>
      <section className="panel separation-list return-list"><header><h2>Itens que saíram</h2><span>{total - checkedCount} pendentes</span></header><div>{orderedItems.map((item) => <article className={item.check_id ? `separation-item separation-item--checked return-condition--${item.return_condition?.toLowerCase()}` : 'separation-item'} key={item.item_id}><span className="separation-state">{item.return_condition === 'DANIFICADO' || item.return_condition === 'EXTRAVIADO' ? <AlertTriangle /> : item.check_id ? <Check /> : <QrCode />}</span><div><strong>{item.internal_code} · {item.description}</strong><small>{item.defect_description || `Condição de saída: ${item.departure_condition}`}</small></div><em>{item.return_condition ? conditions.find(([value]) => value === item.return_condition)?.[1] : 'Pendente'}</em>{item.check_id ? <button disabled={saving} onClick={() => void undo(item.check_id!)}><RotateCcw /> Desfazer</button> : null}</article>)}</div></section>
      <section className="panel return-finalize"><div><h2>Finalizar entrada no galpão</h2><p>Disponíveis voltam ao estoque; danificados abrem manutenção.</p></div><label className="field">Recebido e conferido por<select value={collaboratorId} onChange={(event) => setCollaboratorId(event.target.value)}><option value="">Selecione o colaborador</option>{details.collaborators.map((person) => <option value={person.id} key={person.id}>{person.name} · {person.job_role}</option>)}</select></label><label className="field">Observações<input value={notes} onChange={(event) => setNotes(event.target.value.toLocaleUpperCase('pt-BR'))} /></label><button className="primary" disabled={!complete || !collaboratorId || saving} onClick={() => void finish()}><CheckCircle2 /> {saving ? 'Finalizando…' : 'Finalizar retorno'}</button></section>
    </>}</> : loading ? <p className="empty-state">Carregando retorno…</p> : null}</>
}
