import { type FormEvent, useEffect, useState } from 'react'
import { Building2, Clock3, Database, Save, ShieldCheck } from 'lucide-react'
import { supabase } from '../lib/supabase'

type Settings = { organizationId: string; organizationName: string; role: string }
const roleLabel: Record<string, string> = { owner: 'Proprietário', manager: 'Gestor', operator: 'Operador' }

export function SettingsPage() {
  const [settings, setSettings] = useState<Settings | null>(null); const [name, setName] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  useEffect(() => { let active = true; async function load() { if (!supabase) throw new Error('Serviço não configurado.'); const { data: userData } = await supabase.auth.getUser(); const organizationResult = await supabase.rpc('current_organization_id'); if (organizationResult.error || !organizationResult.data) throw new Error(organizationResult.error?.message ?? 'Empresa ativa não encontrada.'); const [org, member] = await Promise.all([supabase.from('organizations').select('id,name').eq('id', organizationResult.data).single(), supabase.from('organization_members').select('role').eq('organization_id', organizationResult.data).eq('user_id', userData.user?.id ?? '').single()]); if (org.error) throw new Error(org.error.message); if (active) { const value = { organizationId: org.data.id, organizationName: org.data.name, role: member.data?.role ?? 'operator' }; setSettings(value); setName(value.organizationName) } } void load().catch((reason: unknown) => { if (active) setError(reason instanceof Error ? reason.message : 'Não foi possível carregar as configurações.') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [])
  async function save(event: FormEvent) { event.preventDefault(); if (!supabase || !settings || settings.role !== 'owner') return; setSaving(true); setError(''); setSuccess(''); const { error: updateError } = await supabase.from('organizations').update({ name: name.trim() }).eq('id', settings.organizationId); if (updateError) setError(updateError.message); else { setSettings({ ...settings, organizationName: name.trim() }); setSuccess('Configurações salvas com sucesso.') } setSaving(false) }
  if (loading) return <p className="empty-state">Carregando configurações…</p>
  return <div className="management-page settings-page"><div className="title-row"><div><h1>Configurações</h1><p>Identidade e regras da empresa ativa</p></div></div>{error ? <div className="data-error" role="alert">{error}</div> : null}{success ? <div className="success-banner" role="status">{success}</div> : null}
    <div className="settings-grid"><form className="panel settings-form" onSubmit={save}><div className="section-heading"><h2><Building2 /> Empresa</h2></div><label className="field">Nome da empresa<input value={name} required minLength={2} disabled={settings?.role !== 'owner'} onChange={(event) => setName(event.target.value)} /></label><div className="settings-role"><ShieldCheck /><span><small>Seu papel nesta empresa</small><strong>{roleLabel[settings?.role ?? ''] ?? settings?.role}</strong></span></div>{settings?.role === 'owner' ? <button className="primary" disabled={saving || name.trim() === settings.organizationName} type="submit"><Save /> {saving ? 'Salvando…' : 'Salvar alterações'}</button> : <p className="settings-note">Somente o proprietário pode alterar os dados da empresa.</p>}</form>
      <section className="panel settings-rules"><div className="section-heading"><h2><Database /> Regras operacionais</h2></div><article><Clock3 /><span><strong>Folga logística</strong><small>4 horas adicionadas ao retorno previsto para o bloqueio de disponibilidade.</small></span></article><article><ShieldCheck /><span><strong>Status reconciliado</strong><small>O estado dos equipamentos é derivado de saídas, retornos e manutenções.</small></span></article><article><Database /><span><strong>Isolamento de dados</strong><small>Todos os registros são limitados à empresa ativa.</small></span></article></section>
    </div></div>
}
